### ISSUE TITLE
I couldn't run this project

### ISSUE THREAD

**Issue by berkaycapar** [mittagessen/seg#1]
I usually use PyCharm for python. I had installed pip 'pydensecrf', 'torchvision', 'torch>=0.4.0', and 'click'. When I use PyCharm Run, this code is running but I can not get a response. . And when I use PyCharm Terminal I got some errors. 

Exp:
Traceback (most recent call last):
  File "./main.py", line 15, in <module>
    from seg.model import ConvReNet, SqueezeSkipNet, ResSkipNet
ImportError: No module named 'seg'

I get errors when I use the ubuntu terminal too. 

Exp: 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import torchvision.transforms.functional as tf
ImportError: No module named torchvision.transforms.functional
but it's not important because I prefer use to PyCharm. I do not know what to do. Please help me...

**Comment by mittagessen** [comment]
The issue is you haven't installed the seg module first by running `pip install --editable .` or similar, so the absolute import `seg.model` can't be found.

For the second error I guess pycharm puts projects in virtualenvs or something similar to segregate code and dependencies and you haven't activated the pertinent one so pytorch etc. is missing.
